In [1]:
import numpy as np


In [2]:
 array = np.random.randint(0, 50, size=(10, 3))

In [3]:
print(array)

[[31  4 13]
 [46 47 40]
 [10 11 49]
 [14 37 19]
 [27 35 41]
 [20 14 36]
 [32 16 17]
 [37  0 11]
 [ 2  0 49]
 [ 6 20 13]]
